name: 'Backend CI'
on:
  push:
    branches:
    - main
    paths:
    - 'backend/**'
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: 'Backend CI Build'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
        with:
          global-json-file: './backend/global.json'

      - name: Install dependencies
        run: dotnet restore

      - name: Lint
        run: dotnet format --verify-no-changes

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

